Первая и вторая задачи
js-tasks-ru/jsbasic-20220901_ridge87 pull request #1
Opened 2022-09-04 11:18 UTC by timzakirov

2022-09-04 11:18 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2022-09-04 14:51 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-04 14:52 UTC, SinimaWath requested changes

2022-09-04 14:52 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  return (n);
Тут лишние скобки

2022-09-04 14:52 UTC, SinimaWath commented on 1-module/1-task/index.js
> +    var n = 1;
не используй var, это устаревший способ создания переменных. Используй: `let/const`

2022-09-04 14:52 UTC, SinimaWath commented on 1-module/1-task/index.js
> +    for (i=(n-1); i>1; i--) {
для создания переменной i, используй: `let/const`

2022-09-08 14:39 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-08 14:39 UTC, SinimaWath requested changes

2022-09-08 14:39 UTC, SinimaWath commented on 1-module/3-task/index.js
> +    }
Давай тут используем метод slice

2022-09-08 14:39 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  }
`lowerStr.includes('1xbet') || lowerStr.includes('xxx')` - результат операции и так boolean, поэтому if не нужен:
`return lowerStr.includes('1xbet') || lowerStr.includes('xxx')`

2022-09-08 14:39 UTC, SinimaWath commented on 1-module/5-task/index.js
> +    }
Давай используем метод substr/slice

2022-09-11 10:13 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-14 09:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-14 09:21 UTC, SinimaWath approved these changes

2022-09-14 09:22 UTC, merged